# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/shehab/E/college/Semester7/distributed/forked

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/shehab/E/college/Semester7/distributed/forked

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/shehab/E/college/Semester7/distributed/forked/CMakeFiles /media/shehab/E/college/Semester7/distributed/forked/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/shehab/E/college/Semester7/distributed/forked/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named limitleS2

# Build rule for target.
limitleS2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 limitleS2
.PHONY : limitleS2

# fast build rule for target.
limitleS2/fast:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/build
.PHONY : limitleS2/fast

#=============================================================================
# Target rules for targets named limitleS2_autogen

# Build rule for target.
limitleS2_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 limitleS2_autogen
.PHONY : limitleS2_autogen

# fast build rule for target.
limitleS2_autogen/fast:
	$(MAKE) -f CMakeFiles/limitleS2_autogen.dir/build.make CMakeFiles/limitleS2_autogen.dir/build
.PHONY : limitleS2_autogen/fast

GUI/addimagewindow/addimagewindow.o: GUI/addimagewindow/addimagewindow.cpp.o

.PHONY : GUI/addimagewindow/addimagewindow.o

# target to build an object file
GUI/addimagewindow/addimagewindow.cpp.o:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/GUI/addimagewindow/addimagewindow.cpp.o
.PHONY : GUI/addimagewindow/addimagewindow.cpp.o

GUI/addimagewindow/addimagewindow.i: GUI/addimagewindow/addimagewindow.cpp.i

.PHONY : GUI/addimagewindow/addimagewindow.i

# target to preprocess a source file
GUI/addimagewindow/addimagewindow.cpp.i:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/GUI/addimagewindow/addimagewindow.cpp.i
.PHONY : GUI/addimagewindow/addimagewindow.cpp.i

GUI/addimagewindow/addimagewindow.s: GUI/addimagewindow/addimagewindow.cpp.s

.PHONY : GUI/addimagewindow/addimagewindow.s

# target to generate assembly for a file
GUI/addimagewindow/addimagewindow.cpp.s:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/GUI/addimagewindow/addimagewindow.cpp.s
.PHONY : GUI/addimagewindow/addimagewindow.cpp.s

GUI/login/login.o: GUI/login/login.cpp.o

.PHONY : GUI/login/login.o

# target to build an object file
GUI/login/login.cpp.o:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/GUI/login/login.cpp.o
.PHONY : GUI/login/login.cpp.o

GUI/login/login.i: GUI/login/login.cpp.i

.PHONY : GUI/login/login.i

# target to preprocess a source file
GUI/login/login.cpp.i:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/GUI/login/login.cpp.i
.PHONY : GUI/login/login.cpp.i

GUI/login/login.s: GUI/login/login.cpp.s

.PHONY : GUI/login/login.s

# target to generate assembly for a file
GUI/login/login.cpp.s:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/GUI/login/login.cpp.s
.PHONY : GUI/login/login.cpp.s

GUI/mainwidget/mainwidget.o: GUI/mainwidget/mainwidget.cpp.o

.PHONY : GUI/mainwidget/mainwidget.o

# target to build an object file
GUI/mainwidget/mainwidget.cpp.o:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/GUI/mainwidget/mainwidget.cpp.o
.PHONY : GUI/mainwidget/mainwidget.cpp.o

GUI/mainwidget/mainwidget.i: GUI/mainwidget/mainwidget.cpp.i

.PHONY : GUI/mainwidget/mainwidget.i

# target to preprocess a source file
GUI/mainwidget/mainwidget.cpp.i:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/GUI/mainwidget/mainwidget.cpp.i
.PHONY : GUI/mainwidget/mainwidget.cpp.i

GUI/mainwidget/mainwidget.s: GUI/mainwidget/mainwidget.cpp.s

.PHONY : GUI/mainwidget/mainwidget.s

# target to generate assembly for a file
GUI/mainwidget/mainwidget.cpp.s:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/GUI/mainwidget/mainwidget.cpp.s
.PHONY : GUI/mainwidget/mainwidget.cpp.s

GUI/notifications/notifications.o: GUI/notifications/notifications.cpp.o

.PHONY : GUI/notifications/notifications.o

# target to build an object file
GUI/notifications/notifications.cpp.o:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/GUI/notifications/notifications.cpp.o
.PHONY : GUI/notifications/notifications.cpp.o

GUI/notifications/notifications.i: GUI/notifications/notifications.cpp.i

.PHONY : GUI/notifications/notifications.i

# target to preprocess a source file
GUI/notifications/notifications.cpp.i:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/GUI/notifications/notifications.cpp.i
.PHONY : GUI/notifications/notifications.cpp.i

GUI/notifications/notifications.s: GUI/notifications/notifications.cpp.s

.PHONY : GUI/notifications/notifications.s

# target to generate assembly for a file
GUI/notifications/notifications.cpp.s:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/GUI/notifications/notifications.cpp.s
.PHONY : GUI/notifications/notifications.cpp.s

GUI/viewimagewindow/viewimagewindow.o: GUI/viewimagewindow/viewimagewindow.cpp.o

.PHONY : GUI/viewimagewindow/viewimagewindow.o

# target to build an object file
GUI/viewimagewindow/viewimagewindow.cpp.o:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/GUI/viewimagewindow/viewimagewindow.cpp.o
.PHONY : GUI/viewimagewindow/viewimagewindow.cpp.o

GUI/viewimagewindow/viewimagewindow.i: GUI/viewimagewindow/viewimagewindow.cpp.i

.PHONY : GUI/viewimagewindow/viewimagewindow.i

# target to preprocess a source file
GUI/viewimagewindow/viewimagewindow.cpp.i:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/GUI/viewimagewindow/viewimagewindow.cpp.i
.PHONY : GUI/viewimagewindow/viewimagewindow.cpp.i

GUI/viewimagewindow/viewimagewindow.s: GUI/viewimagewindow/viewimagewindow.cpp.s

.PHONY : GUI/viewimagewindow/viewimagewindow.s

# target to generate assembly for a file
GUI/viewimagewindow/viewimagewindow.cpp.s:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/GUI/viewimagewindow/viewimagewindow.cpp.s
.PHONY : GUI/viewimagewindow/viewimagewindow.cpp.s

Peer/main.o: Peer/main.cpp.o

.PHONY : Peer/main.o

# target to build an object file
Peer/main.cpp.o:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/Peer/main.cpp.o
.PHONY : Peer/main.cpp.o

Peer/main.i: Peer/main.cpp.i

.PHONY : Peer/main.i

# target to preprocess a source file
Peer/main.cpp.i:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/Peer/main.cpp.i
.PHONY : Peer/main.cpp.i

Peer/main.s: Peer/main.cpp.s

.PHONY : Peer/main.s

# target to generate assembly for a file
Peer/main.cpp.s:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/Peer/main.cpp.s
.PHONY : Peer/main.cpp.s

limitleS2_autogen/mocs_compilation.o: limitleS2_autogen/mocs_compilation.cpp.o

.PHONY : limitleS2_autogen/mocs_compilation.o

# target to build an object file
limitleS2_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/limitleS2_autogen/mocs_compilation.cpp.o
.PHONY : limitleS2_autogen/mocs_compilation.cpp.o

limitleS2_autogen/mocs_compilation.i: limitleS2_autogen/mocs_compilation.cpp.i

.PHONY : limitleS2_autogen/mocs_compilation.i

# target to preprocess a source file
limitleS2_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/limitleS2_autogen/mocs_compilation.cpp.i
.PHONY : limitleS2_autogen/mocs_compilation.cpp.i

limitleS2_autogen/mocs_compilation.s: limitleS2_autogen/mocs_compilation.cpp.s

.PHONY : limitleS2_autogen/mocs_compilation.s

# target to generate assembly for a file
limitleS2_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/limitleS2_autogen/mocs_compilation.cpp.s
.PHONY : limitleS2_autogen/mocs_compilation.cpp.s

source/Client.o: source/Client.cpp.o

.PHONY : source/Client.o

# target to build an object file
source/Client.cpp.o:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/Client.cpp.o
.PHONY : source/Client.cpp.o

source/Client.i: source/Client.cpp.i

.PHONY : source/Client.i

# target to preprocess a source file
source/Client.cpp.i:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/Client.cpp.i
.PHONY : source/Client.cpp.i

source/Client.s: source/Client.cpp.s

.PHONY : source/Client.s

# target to generate assembly for a file
source/Client.cpp.s:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/Client.cpp.s
.PHONY : source/Client.cpp.s

source/Message.o: source/Message.cpp.o

.PHONY : source/Message.o

# target to build an object file
source/Message.cpp.o:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/Message.cpp.o
.PHONY : source/Message.cpp.o

source/Message.i: source/Message.cpp.i

.PHONY : source/Message.i

# target to preprocess a source file
source/Message.cpp.i:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/Message.cpp.i
.PHONY : source/Message.cpp.i

source/Message.s: source/Message.cpp.s

.PHONY : source/Message.s

# target to generate assembly for a file
source/Message.cpp.s:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/Message.cpp.s
.PHONY : source/Message.cpp.s

source/Peer.o: source/Peer.cpp.o

.PHONY : source/Peer.o

# target to build an object file
source/Peer.cpp.o:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/Peer.cpp.o
.PHONY : source/Peer.cpp.o

source/Peer.i: source/Peer.cpp.i

.PHONY : source/Peer.i

# target to preprocess a source file
source/Peer.cpp.i:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/Peer.cpp.i
.PHONY : source/Peer.cpp.i

source/Peer.s: source/Peer.cpp.s

.PHONY : source/Peer.s

# target to generate assembly for a file
source/Peer.cpp.s:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/Peer.cpp.s
.PHONY : source/Peer.cpp.s

source/Server.o: source/Server.cpp.o

.PHONY : source/Server.o

# target to build an object file
source/Server.cpp.o:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/Server.cpp.o
.PHONY : source/Server.cpp.o

source/Server.i: source/Server.cpp.i

.PHONY : source/Server.i

# target to preprocess a source file
source/Server.cpp.i:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/Server.cpp.i
.PHONY : source/Server.cpp.i

source/Server.s: source/Server.cpp.s

.PHONY : source/Server.s

# target to generate assembly for a file
source/Server.cpp.s:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/Server.cpp.s
.PHONY : source/Server.cpp.s

source/ServiceDirectory.o: source/ServiceDirectory.cpp.o

.PHONY : source/ServiceDirectory.o

# target to build an object file
source/ServiceDirectory.cpp.o:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/ServiceDirectory.cpp.o
.PHONY : source/ServiceDirectory.cpp.o

source/ServiceDirectory.i: source/ServiceDirectory.cpp.i

.PHONY : source/ServiceDirectory.i

# target to preprocess a source file
source/ServiceDirectory.cpp.i:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/ServiceDirectory.cpp.i
.PHONY : source/ServiceDirectory.cpp.i

source/ServiceDirectory.s: source/ServiceDirectory.cpp.s

.PHONY : source/ServiceDirectory.s

# target to generate assembly for a file
source/ServiceDirectory.cpp.s:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/ServiceDirectory.cpp.s
.PHONY : source/ServiceDirectory.cpp.s

source/StegImage.o: source/StegImage.cpp.o

.PHONY : source/StegImage.o

# target to build an object file
source/StegImage.cpp.o:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/StegImage.cpp.o
.PHONY : source/StegImage.cpp.o

source/StegImage.i: source/StegImage.cpp.i

.PHONY : source/StegImage.i

# target to preprocess a source file
source/StegImage.cpp.i:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/StegImage.cpp.i
.PHONY : source/StegImage.cpp.i

source/StegImage.s: source/StegImage.cpp.s

.PHONY : source/StegImage.s

# target to generate assembly for a file
source/StegImage.cpp.s:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/StegImage.cpp.s
.PHONY : source/StegImage.cpp.s

source/UDPClientSocket.o: source/UDPClientSocket.cpp.o

.PHONY : source/UDPClientSocket.o

# target to build an object file
source/UDPClientSocket.cpp.o:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/UDPClientSocket.cpp.o
.PHONY : source/UDPClientSocket.cpp.o

source/UDPClientSocket.i: source/UDPClientSocket.cpp.i

.PHONY : source/UDPClientSocket.i

# target to preprocess a source file
source/UDPClientSocket.cpp.i:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/UDPClientSocket.cpp.i
.PHONY : source/UDPClientSocket.cpp.i

source/UDPClientSocket.s: source/UDPClientSocket.cpp.s

.PHONY : source/UDPClientSocket.s

# target to generate assembly for a file
source/UDPClientSocket.cpp.s:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/UDPClientSocket.cpp.s
.PHONY : source/UDPClientSocket.cpp.s

source/UDPServerSocket.o: source/UDPServerSocket.cpp.o

.PHONY : source/UDPServerSocket.o

# target to build an object file
source/UDPServerSocket.cpp.o:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/UDPServerSocket.cpp.o
.PHONY : source/UDPServerSocket.cpp.o

source/UDPServerSocket.i: source/UDPServerSocket.cpp.i

.PHONY : source/UDPServerSocket.i

# target to preprocess a source file
source/UDPServerSocket.cpp.i:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/UDPServerSocket.cpp.i
.PHONY : source/UDPServerSocket.cpp.i

source/UDPServerSocket.s: source/UDPServerSocket.cpp.s

.PHONY : source/UDPServerSocket.s

# target to generate assembly for a file
source/UDPServerSocket.cpp.s:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/UDPServerSocket.cpp.s
.PHONY : source/UDPServerSocket.cpp.s

source/UDPSocket.o: source/UDPSocket.cpp.o

.PHONY : source/UDPSocket.o

# target to build an object file
source/UDPSocket.cpp.o:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/UDPSocket.cpp.o
.PHONY : source/UDPSocket.cpp.o

source/UDPSocket.i: source/UDPSocket.cpp.i

.PHONY : source/UDPSocket.i

# target to preprocess a source file
source/UDPSocket.cpp.i:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/UDPSocket.cpp.i
.PHONY : source/UDPSocket.cpp.i

source/UDPSocket.s: source/UDPSocket.cpp.s

.PHONY : source/UDPSocket.s

# target to generate assembly for a file
source/UDPSocket.cpp.s:
	$(MAKE) -f CMakeFiles/limitleS2.dir/build.make CMakeFiles/limitleS2.dir/source/UDPSocket.cpp.s
.PHONY : source/UDPSocket.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... limitleS2"
	@echo "... edit_cache"
	@echo "... limitleS2_autogen"
	@echo "... GUI/addimagewindow/addimagewindow.o"
	@echo "... GUI/addimagewindow/addimagewindow.i"
	@echo "... GUI/addimagewindow/addimagewindow.s"
	@echo "... GUI/login/login.o"
	@echo "... GUI/login/login.i"
	@echo "... GUI/login/login.s"
	@echo "... GUI/mainwidget/mainwidget.o"
	@echo "... GUI/mainwidget/mainwidget.i"
	@echo "... GUI/mainwidget/mainwidget.s"
	@echo "... GUI/notifications/notifications.o"
	@echo "... GUI/notifications/notifications.i"
	@echo "... GUI/notifications/notifications.s"
	@echo "... GUI/viewimagewindow/viewimagewindow.o"
	@echo "... GUI/viewimagewindow/viewimagewindow.i"
	@echo "... GUI/viewimagewindow/viewimagewindow.s"
	@echo "... Peer/main.o"
	@echo "... Peer/main.i"
	@echo "... Peer/main.s"
	@echo "... limitleS2_autogen/mocs_compilation.o"
	@echo "... limitleS2_autogen/mocs_compilation.i"
	@echo "... limitleS2_autogen/mocs_compilation.s"
	@echo "... source/Client.o"
	@echo "... source/Client.i"
	@echo "... source/Client.s"
	@echo "... source/Message.o"
	@echo "... source/Message.i"
	@echo "... source/Message.s"
	@echo "... source/Peer.o"
	@echo "... source/Peer.i"
	@echo "... source/Peer.s"
	@echo "... source/Server.o"
	@echo "... source/Server.i"
	@echo "... source/Server.s"
	@echo "... source/ServiceDirectory.o"
	@echo "... source/ServiceDirectory.i"
	@echo "... source/ServiceDirectory.s"
	@echo "... source/StegImage.o"
	@echo "... source/StegImage.i"
	@echo "... source/StegImage.s"
	@echo "... source/UDPClientSocket.o"
	@echo "... source/UDPClientSocket.i"
	@echo "... source/UDPClientSocket.s"
	@echo "... source/UDPServerSocket.o"
	@echo "... source/UDPServerSocket.i"
	@echo "... source/UDPServerSocket.s"
	@echo "... source/UDPSocket.o"
	@echo "... source/UDPSocket.i"
	@echo "... source/UDPSocket.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

