const string StegPassword = "Ay 7aga";
const string DefaultImagePath = "Data/def/defImage.jpeg";
const string PlainImagesDirectory = "Data/images/plain/";
const string StegImagesDirectory = "Data/images/steg/";
const int MAX_MESSAGE_SIZE = 1024;
int PeerServerPort = 4051;
int ServiceDirectoryPort = 4050;
char *ServiceDirectoryAddr = new char[13];
ServiceDirectoryAddr = "10.40.57.172";
